//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronal_Calibration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronal_Calibration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5
        ///-11
        ///-1
        ///-16
        ///+12
        ///+9
        ///-15
        ///+20
        ///+4
        ///+17
        ///-4
        ///-14
        ///+6
        ///-17
        ///+6
        ///-19
        ///-12
        ///+17
        ///-6
        ///-18
        ///+1
        ///+15
        ///-14
        ///+10
        ///-4
        ///-2
        ///+5
        ///+6
        ///+8
        ///+3
        ///+17
        ///-9
        ///+18
        ///-1
        ///+17
        ///-15
        ///+7
        ///-6
        ///-17
        ///-17
        ///+19
        ///+19
        ///-13
        ///+18
        ///-15
        ///+16
        ///+7
        ///-10
        ///-5
        ///+22
        ///+8
        ///-13
        ///+4
        ///+3
        ///+19
        ///+17
        ///-19
        ///-1
        ///-11
        ///+2
        ///+1
        ///-13
        ///+1
        ///+3
        ///-14
        ///+16
        ///-9
        ///+19
        ///+13
        ///-20
        ///+6
        ///+22
        ///+10
        ///+6
        ///+15
        ///-13
        ///-13
        ///-8
        ///+16
        ///+20
        ///-5
        ///+1
        ///+7
        ///+11
        ///-13
        ///+5
        ///-16
        ///-2
        ///-4
        ///+25
        ///-5
        ///-10
        ///-12
        ///-9
        ///+16
        ///-2
        ///-19
        ///-3
        ///-12
        ///+5
        ///+17
        ///+16
        ///+11
        ///+16
        ///+10
        ///+4
        ///+3
        ///+11
        ///-12
        ///+19
        ///+3
        ///+17        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
